### ISSUE TITLE
Node watcher

### ISSUE THREAD

**Issue by bigardone** [slashdotdash/phoenix-react-redux-example#2]
Hi! 
First of all thanks for this awesome example.
I'm a Phoenix newbie and I'm trying to run your project but I'm having a js issue.
After installing everything I have noticed that the dev.exs file is missing the webpack watcher to build all the js and css bundles.

```
watchers: [
    node: ["node_modules/webpack/bin/webpack.js", "--watch-stdin", "--progress", "--colors"]
  ]
```

Are you running webpack independently?
Anyway, after adding this line to the file and starting `phoenix.server` I get this compile error from webpack:

```
ERROR in ./deps/phoenix/web/static/js/phoenix.js
Module build failed: TypeError: /Users/myuser/Documents/projects/elixir/phoenix-react-redux-example/deps/phoenix/web/static/js/phoenix.js: Duplicate declaration "channel"
  454 |
  455 |   channel(topic, chanParams = {}){
> 456 |     let channel = new Channel(topic, chanParams, this)
      |         ^
  457 |     this.channels.push(channel)
  458 |     return channel
  459 |   }
```

Any ideas of what might be causing this?
Thank you very much in advance :)

**Comment by slashdotdash** [comment]
I've just been running webpack on it's own (`webpack --colors --watch`).

I will take a look as to why you're seeing that error.

**Comment by bigardone** [comment]
Thanks for your response :)
I've found the issue... here it is

https://github.com/phoenixframework/phoenix/pull/1332

I seems to be a babel issue.
Thanks!

**Comment by slashdotdash** [comment]
Ah yes, I remember this issue now you've tracked it down. 

I had to manually rename the `channel` variable to `channelInstance` in phoenix.js (as shown in [this commit](https://github.com/matthewlehner/phoenix/commit/8f6a9eb57dbb89a028e64ed160c08d42425efdd7)) to get it working.

**Comment by bigardone** [comment]
Yeah, me too. Sorry for bothering :)
